In [1]:
# Look at the two pre-cleaned datasets.
# Do any further discovery, cleaning
# then merge
import pandas as pd
from os import chdir

chdir("/Users/bencampbell/code_louisville/capstone/louisville-bike-accidents")


path_to_cycling_safety_cleaned = "data/preclean/cycling_safety_louisville_clean.csv"
path_to_LOJIC_cleaned = "data/preclean/LOJIC_cycling_data.csv"

CSAFE = pd.read_csv(path_to_cycling_safety_cleaned)
LOJIC = pd.read_csv(path_to_LOJIC_cleaned)

In [2]:
CSAFE_cols = set(CSAFE.columns.to_list())
LOJIC_cols = set(LOJIC.columns.to_list())
column_intersect = sorted(CSAFE_cols & LOJIC_cols)
column_xor = sorted(CSAFE_cols ^ LOJIC_cols)
all_cols = column_intersect + column_xor

only_CSAFE = CSAFE_cols - LOJIC_cols
only_LOJIC = LOJIC_cols - CSAFE_cols

In [3]:
pd.merge(CSAFE, LOJIC, on='date', how='inner').loc[0]
#len(CSAFE) + len(LOJIC) - 18

investigating_agency_x    LOUISVILLE METRO POLICE DEPT
roadway_number_x                                   NaN
building_number_x                                  NaN
roadway_name_x                                  BARRET
roadway_suffix_x                                   AVE
                                      ...
roadway_character_y                   STRAIGHT & LEVEL
light_condition_y                             DAYLIGHT
secondary_collision_y                            False
fatality_indicator_y                             False
injury_indicator_y                                True
Name: 0, Length: 61, dtype: object

In [4]:
display(only_CSAFE, only_LOJIC)

{'injured', 'killed'}

set()

In [5]:
notes = {'between_street_name_1':None,
 'between_street_name_2':None,
 'building_number':"convert CSAFE value to str(int(...))",
 'date':"done",
 'directional_analysis':"compatible, but no common values",
 'hit_and_run':"done",
 'intersection_roadway_name':None,
 'investigating_agency':'done',
 'latitude':"done",
 'light_condition':'deal with OTHER and Nan values esp. in LOJIC',
 'longitude':"done",
 'manner_of_collision':'done',
 'milepoint':'done',
 'motor_vehicles_involved':'done',
 'roadway_character':'done',
 'roadway_condition':'done',
 'roadway_direction':'done',
 'roadway_name':None,
 'roadway_number':'get rid of whitespace in some strings',
 'roadway_suffix':'done',
 'secondary_collision':'done',
 'units_involved':'done',
 'weather':'done'}

pd.Series(notes)

between_street_name_1                                                None
between_street_name_2                                                None
building_number                      convert CSAFE value to str(int(...))
date                                                                 done
directional_analysis                     compatible, but no common values
hit_and_run                                                          done
intersection_roadway_name                                            None
investigating_agency                                                 done
latitude                                                             done
light_condition              deal with OTHER and Nan values esp. in LOJIC
longitude                                                            done
manner_of_collision                                                  done
milepoint                                                            done
motor_vehicles_involved                                              done
roadway_character                                                    done
roadway_condition                                                    done
roadway_direction                                                    done
roadway_name                                                         None
roadway_number                      get rid of whitespace in some strings
roadway_suffix                                                       done
secondary_collision                                                  done
units_involved                                                       done
weather                                                              done
dtype: object

In [6]:

data = pd.concat((LOJIC.dtypes, CSAFE.dtypes, pd.Series(notes)), axis=1)
data

,0,1,2
investigating_agency,object,object,done
roadway_number,object,object,get rid of whitespace in some strings
building_number,object,float64,convert CSAFE value to str(int(...))
roadway_direction,object,object,done
roadway_name,object,object,None
roadway_suffix,object,object,done
roadway_type,object,object,NaN
intersection_roadway_number,object,object,NaN
intersection_roadway_name,object,object,None
between_street_number_1,object,object,NaN
between_street_name_1,object,object,None
between_street_number_2,object,object,NaN
between_street_name_2,object,object,None
latitude,float64,float64,done
longitude,float64,float64,done
milepoint,float64,float64,done
day_of_week,object,object,NaN
date,object,object,done
units_involved,int64,int64,done
motor_vehicles_involved,int64,int64,done
weather,object,object,done
roadway_condition,object,object,done
hit_and_run,bool,bool,done
directional_analysis,object,object,"compatible, but no common values"
manner_of_collision,object,object,done
roadway_character,object,object,done
light_condition,object,object,deal with OTHER and Nan values esp. in LOJIC
secondary_collision,bool,bool,done
fatality_indicator,bool,bool,NaN
injury_indicator,bool,bool,NaN
killed,NaN,int64,NaN
injured,NaN,int64,NaN

### General notes

Add a column to identify LOJIC data vs. CSAFE data in case there are any further discrepancies to deal with.

In [7]:

def print_table(data):
    header = "| column name | LOJIC dtype | CSAFE dtype | notes |" 
    spaner = "|-------------|-------------|-------------|-------|"
    row = "|{name}|{LOJICDT}|{CSAFEDT}|{note}|"

    ds = lambda s:"" if s == "nan" else s
    dn = lambda s:ds(str(s))

    print(header)
    print(spaner)
    for name in all_cols:
        record = data.loc[name]
        LODT = dn(record[0])
        CSDT = dn(record[1])
        note = record[2]
        print(row.format(name=name, LOJICDT=LODT, CSAFEDT=CSDT, note=note))
    
    
print_table(data)

| column name | LOJIC dtype | CSAFE dtype | notes |
|-------------|-------------|-------------|-------|
|between_street_name_1|object|object|None|
|between_street_name_2|object|object|None|
|between_street_number_1|object|object|nan|
|between_street_number_2|object|object|nan|
|building_number|object|float64|convert CSAFE value to str(int(...))|
|date|object|object|done|
|day_of_week|object|object|nan|
|directional_analysis|object|object|compatible, but no common values|
|fatality_indicator|bool|bool|nan|
|hit_and_run|bool|bool|done|
|injury_indicator|bool|bool|nan|
|intersection_roadway_name|object|object|None|
|intersection_roadway_number|object|object|nan|
|investigating_agency|object|object|done|
|latitude|float64|float64|done|
|light_condition|object|object|deal with OTHER and Nan values esp. in LOJIC|
|longitude|float64|float64|done|
|manner_of_collision|object|object|done|
|milepoint|float64|float64|done|
|motor_vehicles_involved|int64|int64|done|
|roadway_character|object|object|done|
|roadway_condition|object|object|done|
|roadway_direction|object|object|done|
|roadway_name|object|object|None|
|roadway_number|object|object|get rid of whitespace in some strings|
|roadway_suffix|object|object|done|
|roadway_type|object|object|nan|
|secondary_collision|bool|bool|done|
|units_involved|int64|int64|done|
|weather|object|object|done|
|injured||int64|nan|
|killed||int64|nan|

# Data dictionary for joined data

| column name | LOJIC dtype | CSAFE dtype | notes |
|-------------|-------------|-------------|-------|
|between_street_name_1|object|object||
|between_street_name_2|object|object||
|building_number|object|object|convert CSAFE value to str(int(...))|
|date|object|object|done|
|directional_analysis|object|object|compatible, but no common values|
|hit_and_run|bool|bool|done|
|intersection_roadway_name|object|object||
|investigating_agency|object|object|done|
|latitude|float64|float64|done|
|light_condition|object|object|deal with OTHER and Nan values esp. in LOJIC|
|longitude|float64|float64|done|
|manner_of_collision|object|object|done|
|milepoint|float64|float64|done|
|motor_vehicles_involved|int64|int64|done|
|roadway_character|object|object|done|
|roadway_condition|object|object|done|
|roadway_direction|object|object|done|
|roadway_name|object|object||
|roadway_number|object|object|get rid of whitespace in some strings|
|roadway_suffix|object|object|done|
|secondary_collision|bool|bool|done|
|units_involved|int64|int64|done|
|weather|object|object|done|
|between_street_1|object|| similar to between_street_number_1 |
|between_street_2|object|| similar to between_street_number_2|
|between_street_number_1||object| similar to between_street_1|
|between_street_number_2||object| similar to between_street_2|
|between_street_suffix_1||object||
|between_street_suffix_2||object||
|collision_status_code||object||
|council_district|int64|||
|day_of_week|object|| generate day_of_week for CSAFE |
|directional_analysis_code||float64||
|fatality_indicator|bool||generate fatality_indicator for CSAFE|
|incident_id|int64|||
|injured||int64||
|injury_indicator|bool||generate injury_indicator foor CSAFE|
|intersection_roadway|object||similar to CSAFE[intersection_roadway_number] rename to that to make it compatible|
|intersection_roadway_number||object| similar to LOJIC[intersection_roadway]; no rename|
|intersection_roadway_suffix||object||
|killed||int64||
|light_condition_code||float64|numeric code not present in LOJIC|
|local_code||object||
|manner_of_collision_code||float64||
|master_file_number||int64||
|mode|object|||
|object_id|int64|||
|owner|object|||
|ramp_from_roadway_id||float64||
|ramp_to_roadway_id||float64||
|road_classification|object|||
|roadway_character_code||float64|numeric code not present in LOJIC|
|roadway_condition_code||float64|numeric code not present in LOJIC|
|roadway_type||object||
|roadway_type_code||float64||
|weather_code||float64|numeric code not present in LOJIC|

# Common column names:
`['between_street_name_1', 'between_street_name_2', 'building_number', 'date', 'directional_analysis',
    'hit_and_run', 'intersection_roadway_name', 'intersection_roadway_number', 'investigating_agency', 'latitude', 'light_condition', 'longitude', 'manner_of_collision', 'milepoint', 'motor_vehicles_involved', 'roadway_character', 'roadway_condition', 'roadway_direction', 'roadway_name', 'roadway_number', 'roadway_suffix', 'roadway_type',
    'secondary_collision', 'units_involved', 'weather']`

In [8]:
def pair(col_name):
    return pd.DataFrame({"CSAFE":CSAFE[col_name], "LOJIC": LOJIC[col_name]})

def join(col_name):
    return pd.concat((CSAFE[col_name], LOJIC[col_name]), axis=0)

In [9]:
pair('between_street_name_1').dropna()

         CSAFE       LOJIC
2    GRINSTEAD   STALLINGS
13    CARDINAL     LONGEST
28   SOUTHLAND      WILSON
32      TAYLOR     LORETTA
51     MADISON  INDUSTRIAL
114     BAXTER   BLUE VALE

In [10]:
pair('between_street_name_2').dropna()

                 CSAFE                  LOJIC
2            GRINSTEAD                 KLAGES
13               BLOOM              BEECHWOOD
28              WABASH  DR WILLIAM G WEATHERS
32            WHITMORE                 KREMER
51   OLD HARRODS CREEK                 ULRICH
114          BARDSTOWN           AUTUMN RIDGE

In [11]:
DA = pair('directional_analysis')
DA["CSAFE"].unique()
DA["LOJIC"].unique() 
# Different sets of values, no intersection. 
# Maybe I have to drop this; might not be useful.

array(['COLLISION WITH BICYCLE IN INTERSECTION',
       'COLLISION WITH BICYCLIST NON INTERSECTION', nan,
       'COLLISION WITH PEDESTRIAN NON - INTERSECTION',
       'COLLISION WITH PEDESTRIAN IN INTERSECTION',
       'OTHER INTERSECTION COLLISIONS',
       '1 VEHICLE ENTERING/LEAVING ENTRANCE',
       'OTHER ROADWAY OR MID-BLOCK COLLISION'], dtype=object)

In [12]:
DA.apply(lambda x:x.value_counts(dropna=False))

                                              CSAFE   LOJIC
1 VEHICLE ENTERING/LEAVING ENTRANCE             NaN     1.0
COLLISION WITH BICYCLE                        704.0     NaN
COLLISION WITH BICYCLE IN INTERSECTION          NaN    45.0
COLLISION WITH BICYCLIST                      569.0     NaN
COLLISION WITH BICYCLIST NON INTERSECTION       NaN    57.0
COLLISION WITH PEDESTRIAN IN INTERSECTION       NaN     2.0
COLLISION WITH PEDESTRIAN NON - INTERSECTION    NaN     2.0
OTHER INTERSECTION COLLISIONS                   NaN     2.0
OTHER ROADWAY OR MID-BLOCK COLLISION            NaN     1.0
NaN                                             NaN  1163.0

In [13]:
RN = pair("roadway_number")
join("roadway_number").value_counts()

roadway_number
US0031E    81
US0031W    72
KY1020     55
KY0061     42
US0060     36
US0150     35
US0060A    32
KY0864     23
KY1931     18
KY0155     17
KY1865     16
KY1065     13
KY1447     12
KY1747     11
US0042     10
US0031      9
KY1932      8
KY0907      7
KY2050      7
KY1934      7
KY2049      6
KY2048      6
KY0146      5
I 0264      5
KY3082      5
KY2052      5
KY1703      5
KY1450      5
I 0065      4
KY2051      4
KY1727      4
KY0841      4
KY2054      4
KY1819      4
KY3064      4
KY1631      3
KY2251      3
KY1142      3
KY2055      2
KY2845      2
KY0913      2
KY2860      1
I 0064      1
KY3077      1
KY1230      1
KY2053      1
KY0148      1
I 0265      1
KY1851      1
Name: count, dtype: int64

In [14]:
LOJIC['between_street_number_1'].dropna() # Alphanumeric roadway designator like KY 2049, US31W
CSAFE['between_street_number_1'].dropna() # Same thing
LOJIC['between_street_number_2'].dropna()
CSAFE['between_street_number_2'].dropna()
# These all have the same kind of alphanumeric data. 
# Rectify these names to make them compatible
# * make sure this doesn't clash with anything. 

# DONE

4        KY2048
5        I 0264
42       KY1065
63       KY1020
74       US0060
76       US0150
106      KY0061
114     US0031E
115     US0060A
128      KY1020
160      KY2054
250      US0150
264      KY0061
272      KY1865
293      KY0864
299      US0150
311     US0031E
316     US0031E
329      KY0061
364      KY0864
373     US0031E
406      KY0061
419      US0150
427      KY1703
434     US0060A
436      US0150
443      KY2048
471      KY1020
496     US0031W
527      KY0061
584     US0031E
590     US0060A
627      KY2251
638      KY0061
676      KY1931
677      US0060
681     US0031W
694      KY1065
698      US0150
704      KY1931
741      KY0061
760      KY1020
784     US0031W
811      KY2840
852      US0150
938      KY2048
980     US0060A
984      KY0061
1082     KY2049
1101     KY2860
1157     I 0065
1260     I 0265
Name: between_street_number_2, dtype: object

In [15]:
CSAFE['killed'].apply(lambda x:True if x > 0 else False).value_counts()

killed
False    1262
True       11
Name: count, dtype: int64

In [16]:
d =CSAFE['date'][0]
pd.Timestamp(d).day_name()

'Wednesday'

## Date overlap

Conveniently, my two data sets have an overlap in terms of the date ranges they cover. "CSAFE" has records from 2010-2017 and LOJIC has records from 2016 to 2023. I'll check these records to see if there are any problems merging them.

Also, I may be able to gain insights into how each dataset codes different information.l

In [17]:
import numpy as np

CSAFE['date'] = CSAFE['date'].apply(pd.Timestamp)
LOJIC['date'] = LOJIC['date'].apply(pd.Timestamp)

# I'm loading data from CSV, which stores Timestamps as strings.
# I have to convert them back to pd.Timestamp if I want to use comparisons
# This is annoying. Perhaps break up date/time into year/month/day/hour/etc... columns?

# Find all Timestamps that are common between all my data.
date_intersect = np.intersect1d(CSAFE['date'], LOJIC['date'])
date_intersect.sort()
date_intersect

# Select the rows corresponding to the common Timestamps from each dataframe
# With these dataframes, set the index to "date" since that's what we'll be comparing against. 
CSAFE_intersect = CSAFE[CSAFE['date'].isin(date_intersect)]
LOJIC_intersect = LOJIC[LOJIC['date'].isin(date_intersect)]
CS = CSAFE_intersect.set_index('date').sort_index()
LO = LOJIC_intersect.set_index('date').sort_index()
#assert all(CSAFE_intersect.index == LOJIC_intersect.index)
cols = list(np.intersect1d(CSAFE_intersect.columns, LOJIC_intersect.columns))

In [18]:
def do(date_index):
    date = date_intersect[date_index]

    CS = CSAFE_intersect[CSAFE_intersect.date == date]
    LO = LOJIC_intersect[LOJIC_intersect.date == date]
    df = pd.concat((CS, LO)).transpose()
    df['TEST'] = df.iloc[:,0] == df.iloc[:,1]
    dropnulls = df[(df.iloc[:,0].notnull() | df.iloc[:,1].notnull())]
    return dropnulls[dropnulls['TEST'] == False]

In [19]:
date_intersect = np.intersect1d(CSAFE['date'], LOJIC['date'])
CSAFE_intersect = CSAFE[CSAFE['date'].isin(date_intersect)]
LOJIC_intersect = LOJIC[LOJIC['date'].isin(date_intersect)]

m = pd.merge(CSAFE_intersect, LOJIC_intersect, on='date', how='outer', suffixes=("_CSAFE", "_LOJIC"))

column_intersect = list(np.intersect1d(CSAFE.columns, LOJIC.columns))
column_intersect.remove('date')
column_intersect

['between_street_name_1',
 'between_street_name_2',
 'between_street_number_1',
 'between_street_number_2',
 'building_number',
 'day_of_week',
 'directional_analysis',
 'fatality_indicator',
 'hit_and_run',
 'injury_indicator',
 'intersection_roadway_name',
 'intersection_roadway_number',
 'investigating_agency',
 'latitude',
 'light_condition',
 'longitude',
 'manner_of_collision',
 'milepoint',
 'motor_vehicles_involved',
 'roadway_character',
 'roadway_condition',
 'roadway_direction',
 'roadway_name',
 'roadway_number',
 'roadway_suffix',
 'roadway_type',
 'secondary_collision',
 'units_involved',
 'weather']

As it turns out, there's no meaningful information in LOJIC for the overlapping records which isn't already in CSAFE. To join these datasets, I'll first remove the operlap from LOJIC, then concat LOJIC to CSAFE.

In [20]:
to_remove = LOJIC[LOJIC['date'].isin(date_intersect)].index
LOJIC_clean = LOJIC.drop(to_remove, axis=0)

In [21]:
full = pd.concat((CSAFE, LOJIC_clean), ignore_index=True)
full

,investigating_agency,roadway_number,building_number,roadway_name,roadway_suffix,roadway_direction,milepoint,intersection_roadway_number,intersection_roadway_name,between_street_number_1,...,manner_of_collision,roadway_character,light_condition,secondary_collision,date,latitude,longitude,injury_indicator,fatality_indicator,day_of_week
0,LOUISVILLE METRO POLICE DEPT,US0042,NaN,BROWNSBORO,RD,NaN,1.744,NaN,JANE,NaN,...,SINGLE VEHICLE,STRAIGHT & GRADE,DARK-HWY LIGHTED/ON,False,2010-01-13 10:00:00-05:00,38.258551,-85.703576,False,False,WEDNESDAY
1,LOUISVILLE METRO POLICE DEPT,NaN,NaN,ZORN,AVE,NaN,1.476,I 0071,I71 N EXIT2 OFF RAMP TO ZORN AVE,NaN,...,SINGLE VEHICLE,CURVE & LEVEL,DAYLIGHT,False,2010-01-13 13:40:00-05:00,38.273995,-85.696572,True,False,WEDNESDAY
2,LOUISVILLE METRO POLICE DEPT,NaN,NaN,PETERSON,AVE,S,0.278,NaN,NaN,NaN,...,SINGLE VEHICLE,STRAIGHT & GRADE,DAYLIGHT,False,2010-01-15 15:50:00-05:00,38.250012,-85.697265,False,False,FRIDAY
3,LOUISVILLE METRO POLICE DEPT,NaN,NaN,GEORGETOWN,PL,NaN,0.051,NaN,CONN,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DAYLIGHT,False,2010-02-02 06:11:00-05:00,38.195890,-85.793380,False,False,TUESDAY
4,LOUISVILLE METRO POLICE DEPT,NaN,NaN,PEE WEE REESE,RD,NaN,2.116,NaN,NaN,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DAYLIGHT,False,2010-02-05 18:20:00-05:00,38.246136,-85.664685,False,False,FRIDAY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,LYNDON POLICE DEPARTMENT,NaN,NaN,LA GRANGE,RD,NaN,0.706,NaN,NaN,NaN,...,ANGLE,STRAIGHT & LEVEL,DAYLIGHT,False,2023-08-15 07:19:00-04:00,38.265397,-85.594638,False,True,TUESDAY
1370,LOUISVILLE METRO POLICE DEPT,NaN,NaN,FEGENBUSH,LN,NaN,0.233,NaN,NORFOLK,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DAYLIGHT,False,2023-08-21 14:57:00-04:00,38.183875,-85.638266,True,False,MONDAY
1371,LOUISVILLE METRO POLICE DEPT,NaN,NaN,DELOR,AVE,NaN,0.937,NaN,PACKARD,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DAYLIGHT,False,2023-08-30 07:49:00-04:00,38.210348,-85.733536,True,False,WEDNESDAY
1372,LOUISVILLE METRO POLICE DEPT,NaN,NaN,OLD BROWNSBORO HILLS,RD,NaN,0.131,NaN,NaN,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DAYLIGHT,False,2023-09-01 16:20:00-04:00,38.301243,-85.595479,False,True,FRIDAY
1373,LOUISVILLE METRO POLICE DEPT,KY1065,NaN,OUTER,LOOP,NaN,6.220,NaN,NaN,NaN,...,SINGLE VEHICLE,STRAIGHT & LEVEL,DARK-HWY NOT LIGHTED,False,2023-09-22 23:25:00-04:00,38.138261,-85.683783,False,True,FRIDAY

## Signalized intersections
Now to bring in data from the signalized intersections dataset

In [27]:
path_to_signalized_intersectons = "/Users/bencampbell/code_louisville/capstone/louisville-bike-accidents/data/preclean/signalized_intersections.csv"
SIGNALS = pd.read_csv(path_to_signalized_intersectons)

In [28]:
SIGNALS

,longitude,latitude,main_street,cross_street,route_number,milepoint,owner,type
0,-85.499337,38.270632,OLD HENRY,I 265 RAMP,KY-3084,1.250,KYTC,1
1,-85.498479,38.241589,SHELBYVILLE,BECKLEY WOODS,US 60,12.291,KYTC,1
2,-85.493550,38.240517,SHELBYVILLE,LAKE FOREST,US-60,12.580,KYTC,1
3,-85.570212,38.311002,BROWNSBORO,I 265 RAMP,KY-22,3.700,KYTC,1
4,-85.627965,38.283916,HERR,LIME KILN,KY-22,0.440,KYTC,1
...,...,...,...,...,...,...,...,...
1086,-85.546671,38.147768,BILLTOWN RD,I 265 RAMP,KY-1819,5.290,KYTC,1
1087,-85.495722,38.271982,OLD HENRY RD,TERRA CROSSING BLVD,KY-3084,1.480,KYTC,1
1088,-85.551047,38.296855,WESTPORT RD,I 265 RAMP,KY-1447,6.470,KYTC,1
1089,-85.614517,38.125808,BEULAH CHURCH RD,I 265 RAMP,KY-864,3.450,KYTC,1
1090,-85.697942,38.275734,ZORN AVE,I 71 RAMP,NaN,NaN,KYTC,1

In [29]:
SIGNALS

,longitude,latitude,main_street,cross_street,route_number,milepoint,owner,type
0,-85.499337,38.270632,OLD HENRY,I 265 RAMP,KY-3084,1.250,KYTC,1
1,-85.498479,38.241589,SHELBYVILLE,BECKLEY WOODS,US 60,12.291,KYTC,1
2,-85.493550,38.240517,SHELBYVILLE,LAKE FOREST,US-60,12.580,KYTC,1
3,-85.570212,38.311002,BROWNSBORO,I 265 RAMP,KY-22,3.700,KYTC,1
4,-85.627965,38.283916,HERR,LIME KILN,KY-22,0.440,KYTC,1
...,...,...,...,...,...,...,...,...
1086,-85.546671,38.147768,BILLTOWN RD,I 265 RAMP,KY-1819,5.290,KYTC,1
1087,-85.495722,38.271982,OLD HENRY RD,TERRA CROSSING BLVD,KY-3084,1.480,KYTC,1
1088,-85.551047,38.296855,WESTPORT RD,I 265 RAMP,KY-1447,6.470,KYTC,1
1089,-85.614517,38.125808,BEULAH CHURCH RD,I 265 RAMP,KY-864,3.450,KYTC,1
1090,-85.697942,38.275734,ZORN AVE,I 71 RAMP,NaN,NaN,KYTC,1

In [38]:
print(pd.io.sql.get_schema(full, 'data'))

CREATE TABLE "data" (
"investigating_agency" TEXT,
  "roadway_number" TEXT,
  "building_number" TEXT,
  "roadway_name" TEXT,
  "roadway_suffix" TEXT,
  "roadway_direction" TEXT,
  "milepoint" REAL,
  "intersection_roadway_number" TEXT,
  "intersection_roadway_name" TEXT,
  "between_street_number_1" TEXT,
  "between_street_name_1" TEXT,
  "between_street_number_2" TEXT,
  "between_street_name_2" TEXT,
  "units_involved" INTEGER,
  "motor_vehicles_involved" INTEGER,
  "killed" REAL,
  "injured" REAL,
  "weather" TEXT,
  "roadway_condition" TEXT,
  "hit_and_run" INTEGER,
  "roadway_type" TEXT,
  "directional_analysis" TEXT,
  "manner_of_collision" TEXT,
  "roadway_character" TEXT,
  "light_condition" TEXT,
  "secondary_collision" INTEGER,
  "date" TIMESTAMP,
  "latitude" REAL,
  "longitude" REAL,
  "injury_indicator" INTEGER,
  "fatality_indicator" INTEGER,
  "day_of_week" TEXT
)